# Generated by Django 5.1 on 2024-09-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.CharField(blank=True, default='No registrado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, default='No registrado', max_length=255, null=True, unique=True),
        ),
    ]
