# Generated by Django 5.1 on 2024-09-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_linkedin_user_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
