# Generated by Django 5.1 on 2024-09-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_user_visible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
