# Generated by Django 5.1 on 2024-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('linkedin', models.CharField(blank=True, default='No registrado', max_length=255, null=True)),
                ('orcid', models.CharField(blank=True, default='No registrado', max_length=255, null=True, unique=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
